title: JoLou's Website
description: >- 
  Economics and statistics calculators for undergraduate/graduate studies. Automated numeric calculations, graphic visualization, and model simulations in microeconomics, macroeconomics, econometrics, finance, and more!
